language: go

go:
  - 1.12.x

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

os:
  - linux

env:
  - GO111MODULE=on

# this is run on all arch
script: go test -short -race ./... -v

# this is run only on linux_amd64
jobs:
  include:
    - os: linux
      arch: amd64
    - name: "build"
      script: go build ./...
    - name: "lint"
      install: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
      script: golangci-lint run --deadline=5m
    - name: "coverage"
      script:
      - go test -short -coverprofile=coverage.txt -covermode=atomic ./...
      after_success: bash <(curl -s https://codecov.io/bash)
