language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

arch:
  - amd64
  - arm64

matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64

jobs:
  include:
    - name: "build"
      script: go build ./...
    - name: "lint"
      install: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
      script: golangci-lint run --deadline=7m
    - name: "coverage"
      script:
      - go test -short -coverprofile=coverage.txt -covermode=atomic ./...
      after_success: bash <(curl -s https://codecov.io/bash)
    - name: "race"
      script:
      - go test -short -race ./... -v
