# GitHub Actions - CI for Go with just builders and tests.  Use cover.yml and linters.yml for coverage and linting.
# Author: Montgomery Edwards⁴⁴⁸ (github.com/x448)
name: ci
on: [push]
jobs:

  # Test on various OS with default Go version. Specifying Go version causes too much slowdown as of January 2020.
  tests:
    name: Test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build project
      run: go build ./...
    - name: Run tests
      run: |
        go version
        go test -short -race -v ./...

  ## Codecov.io is deprecated. IMHO, codecov.io asked for too much info.
  ## Use https://github.com/x448/.github/workflows/cover.yml (go test -cover plus python = privacy).

